---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkoperator
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: sparkoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/version: v1beta2-1.0.1-2.4.4
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v1beta2-1.0.1-2.4.4
    spec:
      serviceAccountName: sparkoperator
      imagePullSecrets:
        []
      volumes:
        - name: webhook-certs
          secret:
            secretName: spark-webhook-certs
      containers:
      - name: sparkoperator
        image: gcr.io/spark-operator/spark-operator:v1beta2-1.0.1-2.4.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook-certs
        ports:
          - containerPort: 10254
        args:
        - -v=2
        - -namespace=
        - -ingress-url-format=
        - -controller-threads=10
        - -resync-interval=30
        - -logtostderr
        - -enable-metrics=true
        - -metrics-labels=app_type
        - -metrics-port=10254
        - -metrics-endpoint=/metrics
        - -metrics-prefix=
        - -enable-webhook=true
        - -webhook-svc-namespace=spark-operator
        - -webhook-port=8080
        - -webhook-svc-name=sparkoperator-webhook
        - -webhook-config-name=sparkoperator-sparkoperator-webhook-config